export const businesses = [
  {
    ubid: "KA-2024-BIZ-001",
    name: "Ravi Enterprises Pvt Ltd",
    owner: "Ravi Kumar",
    city: "Bengaluru",
    sector: "Manufacturing",
    gstin: "29AABCR1234D1Z5",
    udyam: "UDYAM-KA-01-0012345",
    municipalLicence: "BBMP/2022/TL/45231",
    fssai: null,
    complianceScore: 87,
    turnover: [42, 51, 48, 63, 71, 68],
    status: "Active",
    alerts: [],
    compliance: [
      { department: "GST", status: "compliant", expiresAt: null, note: "Filed up to date" },
      { department: "Udyam", status: "compliant", expiresAt: null, note: "Registered MSME" },
      { department: "Municipal Licence", status: "compliant", expiresAt: "2025-03-15", note: "Valid" },
      { department: "FSSAI", status: "pending", expiresAt: null, note: "Not applicable" },
    ],
    directors: ["Ravi Kumar", "Sunitha Kumar"],
    address: "Plot 42, KIADB Industrial Area, Bengaluru North, Karnataka 560045",
    registrationDate: "2019-04-12",
  },
  {
    ubid: "KA-2024-BIZ-002",
    name: "Meena Textiles",
    owner: "Meena Sharma",
    city: "Hubli",
    sector: "Textiles",
    gstin: "29AABCM5678E1Z3",
    udyam: "UDYAM-KA-10-0067891",
    municipalLicence: "HMC/2021/SL/8823",
    fssai: null,
    complianceScore: 64,
    turnover: [28, 31, 29, 35, 38, 34],
    status: "Action Required",
    alerts: [
      "Municipal Licence expires in 30 days",
      "GST filing due next week",
    ],
    compliance: [
      { department: "GST", status: "warning", expiresAt: "2025-05-20", note: "Filing due next week" },
      { department: "Udyam", status: "compliant", expiresAt: null, note: "Registered MSME" },
      { department: "Municipal Licence", status: "warning", expiresAt: "2025-06-04", note: "Expires in 30 days" },
      { department: "FSSAI", status: "non_compliant", expiresAt: null, note: "Pending — not yet applied" },
    ],
    directors: ["Meena Sharma"],
    address: "Door No. 14/A, Textile Nagar, Hubli, Karnataka 580029",
    registrationDate: "2021-08-03",
  },
  {
    ubid: "KA-2024-BIZ-003",
    name: "Hubli Foods Co",
    owner: "Suresh Patil",
    city: "Hubli",
    sector: "Food & Beverage",
    gstin: null,
    udyam: "UDYAM-KA-10-0098234",
    municipalLicence: "HMC/2023/TL/1102",
    fssai: null,
    complianceScore: 41,
    turnover: [18, 22, 19, 24, 41, 43],
    status: "Non-Compliant",
    alerts: [
      "GST registration required — turnover crossed Rs.40L",
      "FSSAI licence not found",
    ],
    compliance: [
      { department: "GST", status: "non_compliant", expiresAt: null, note: "Registration required — turnover > Rs.40L" },
      { department: "Udyam", status: "compliant", expiresAt: null, note: "Registered MSME" },
      { department: "Municipal Licence", status: "compliant", expiresAt: "2025-12-31", note: "Valid" },
      { department: "FSSAI", status: "non_compliant", expiresAt: null, note: "Licence not found — mandatory for food businesses" },
    ],
    directors: ["Suresh Patil", "Kavitha Patil"],
    address: "Survey No. 88, Gokul Road, Hubli, Karnataka 580030",
    registrationDate: "2023-01-17",
  },
];

export const intelligenceAlerts = [
  {
    id: "ALERT-001",
    severity: "high",
    category: "Compliance Anomaly",
    title: "Sudden drop in GST filings — Textile sector, Dharwad",
    description: "23% decline in GST filings detected in the Textile sector across Dharwad district this month compared to the 6-month average. Possible cash-flow distress or evasion pattern.",
    district: "Dharwad",
    sector: "Textiles",
    affectedCount: 47,
    createdAt: "2025-05-03T08:30:00Z",
  },
  {
    id: "ALERT-002",
    severity: "medium",
    category: "Threshold Breach",
    title: "14 businesses in Hubli crossed Rs.40L turnover threshold",
    description: "14 businesses in Hubli have crossed the Rs.40 lakh annual turnover threshold and are now liable for mandatory GST registration. Outreach required.",
    district: "Hubli-Dharwad",
    sector: null,
    affectedCount: 14,
    createdAt: "2025-05-02T14:15:00Z",
  },
  {
    id: "ALERT-003",
    severity: "high",
    category: "Fraud Indicator",
    title: "Cluster of 6 businesses share same registered address",
    description: "Six distinct businesses registered under separate UBIDs share identical registered address at 22B, Industrial Layout, Belagavi. Possible shell entity arrangement — investigation recommended.",
    district: "Belagavi",
    sector: null,
    affectedCount: 6,
    createdAt: "2025-05-01T10:00:00Z",
  },
];

export const platformStats = {
  totalBusinesses: 473291,
  unifiedToday: 1847,
  complianceRate: 94.2,
  activeAlerts: 3,
  districtsActive: 31,
  sectorsMonitored: 18,
};

export const sectorAnalytics = [
  { district: "Bengaluru Urban", sector: "IT/Software", complianceRate: 98.4, totalBusinesses: 42100, compliantCount: 41386 },
  { district: "Bengaluru Urban", sector: "Manufacturing", complianceRate: 91.2, totalBusinesses: 18400, compliantCount: 16781 },
  { district: "Mysuru", sector: "Tourism", complianceRate: 87.6, totalBusinesses: 9200, compliantCount: 8059 },
  { district: "Hubli-Dharwad", sector: "Textiles", complianceRate: 74.3, totalBusinesses: 12800, compliantCount: 9510 },
  { district: "Hubli-Dharwad", sector: "Food & Beverage", complianceRate: 69.1, totalBusinesses: 8300, compliantCount: 5735 },
  { district: "Belagavi", sector: "Manufacturing", complianceRate: 82.5, totalBusinesses: 11200, compliantCount: 9240 },
  { district: "Mangaluru", sector: "Trade & Commerce", complianceRate: 89.7, totalBusinesses: 14600, compliantCount: 13096 },
  { district: "Shivamogga", sector: "Agriculture Processing", complianceRate: 71.8, totalBusinesses: 6400, compliantCount: 4595 },
];

export const rawRecordsForDemo = [
  // Business 1 variants
  { source: "GST Portal", name: "Ravi Enterprises Pvt Ltd", pan: "AABCR1234D", address: "Plot 42, KIADB Industrial Area, Bengaluru" },
  { source: "Udyam Registry", name: "Ravi Enterprises Private Limited", pan: "AABCR1234D", address: "Plot 42, KIADB Indl Area, Blr North" },
  { source: "Municipal Database", name: "RAVI ENT PVT LTD", pan: null, address: "42, Bangalore Industrial Estate" },
  // Business 2 variants
  { source: "GST Portal", name: "Meena Textiles", pan: "AABCM5678E", address: "14/A, Textile Nagar, Hubli" },
  { source: "Udyam Registry", name: "M. Textiles", pan: "AABCM5678E", address: "Door 14A, Hubli 580029" },
  { source: "Municipal Database", name: "Meena Textile Works", pan: null, address: "Textile Nagar Hubli Karnataka" },
  // Business 3 variants
  { source: "GST Portal", name: "Hubli Foods Co", pan: null, address: "Survey 88, Gokul Road, Hubli" },
  { source: "Udyam Registry", name: "Hubli Food Company", pan: null, address: "Gokul Road, Hubli, KA 580030" },
  { source: "FSSAI Registry", name: "HublifoOds", pan: null, address: "88, Gokul Rd, Hubli" },
];
